name: HACS Validation

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install HACS Tools
        run: |
          python -m pip install --upgrade pip
          pip install hacs-tools

      - name: Run HACS validation
        run: |
          python -m hacs_tools.validate
