name: Hassfest Check

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Home Assistant CLI
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant

      - name: Run hassfest
        run: |
          hassfest .
